### PR TITLE
Function for shiny notification with news

### PR DESCRIPTION
**Pull request by teofiln**
Functions that wrap `shiny::showNotification` and `shiny::withProgress` so that a notification pops up with a random headline from the desired news source.

### CODE REVIEW

**Comment by teofiln** [comment]
Two things to check on:

1. whether the `seealso` links work -- they don't for me but maybe because dev documentation? ..
2. for some reason, when using a custom `rss_table` we get this as the column name in the resulting tibble:

image

**Comment by teofiln** [comment]
@novica :point_up:

**Comment by novica** [comment]
@teofiln is this still relevant?

**Comment by teofiln** [comment]
nope.

**Pull request closed without merging**
